version: "3.4"

services:
  avalanchecovidxraylive:
    container_name: covidxray-continualai
    image: avalanchecovidxraylive
    build:
      context: .
      dockerfile: ./Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
